### ISSUE TITLE
Support component name in DaprChatClient constructor

### ISSUE THREAD

**Issue by bibryam** [dapr/dapr-agents#108]
### Context
The current `DaprChatClient` does not allow specifying a custom Dapr component name, requiring env variable every time.
Users should be able to instantiate the client with a specific component name that matches a Dapr component.

example

give component like this

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: claude
spec:
  type: conversation.anthropic
  metadata:
    - name: key
      value: foo-OyXzRQAA
    - name: model
      value: claude-3-5-sonnet-20240620
    - name: cacheTTL
      value: 10m
```

Users can instantiate the client with a custom component name: 

`llm = DaprChatClient(component="claude")`.
