### ISSUE TITLE
Default LLM Client Initialization for `DurableAgent`

### ISSUE THREAD

**Issue by bibryam** [dapr/dapr-agents#141]
### Context

Creating agents currently involves multiple configurations in different places, which is not aligned with standard Python and AI development practices. To match user expectations from similar frameworks, agent setup should be simplified through intelligent defaults for LLM selection, component usage, and credential injection.<br><br>This change is proposed only for DurableAgent which should use Dapr for all interactions by default.<br>The Agent class, should remain as is, not use Dapr by default - as it is not for durable, reliable scenarios.

### Current Behavior (Explicit Configuration)

`.env`:

```ini
DAPR_LLM_COMPONENT_DEFAULT=openai
```

Dapr Component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  metadata:
    - name: key
      value: <OPENAI_API_KEY>
    - name: model
      value: gpt-4-turbo
```

Python:

```python
agent = DurableAgent(
    name="TravelBuddy",
    llm=DaprChatClient()
)
```

### Desired Behavior (Minimal Configuration)

I should be able to set LLM key as env variable or in the .env file

`.env`:

```ini
OPENAI_API_KEY=foo
# no need for component name here
```

Dapr Component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  metadata:
# if no key present, then check for env variable
    - name: model
      value: gpt-4-turbo
```

Python:

```python
agent = DurableAgent(
    name="TravelBuddy",
    # default to daprchatclient
)
```

### Acceptance Criteria

* If no `llm` is passed to `Agent`, it should default to `DaprChatClient`.
* `DaprChatClient` should:
  * Use the only available `ConversationComponent` if exactly one is found.
  * Raise an exception if multiple components are present and no name is specified.
* `ConversationComponent` of type `conversation.openai` should use `OPENAI_API_KEY` if no `key` is specified in metadata.
* Other conversation component types should check for respective env variables: OPENAI_API_KEY,ANTHROPIC_API_KEY,COHERE_API_KEY,MISTRAL_API_KEY, etc.
* Explicitly provided keys in metadata should always take precedence over environment variables.
